export const eventTypesListOptions = [
	{ value: 'concerts', label: 'Концерты' },
	{ value: 'party', label: 'Вечеринки' },
	{ value: 'business', label: 'Бизнес' },
	{ value: 'it_internet', label: 'Ит и интернет' },
	{ value: 'exhibitions', label: 'Выставки' },
	{ value: 'cinema', label: 'Кино' },
	{ value: 'food', label: 'Еда' },
	{ value: 'education', label: 'Образование' },
	{ value: 'art_culture', label: 'Искусство и культура' },
	{ value: 'for_children', label: 'Для детей' },
	{ value: 'psychology', label: 'Психология и саморазвитие' },
	{ value: 'other_events', label: 'Другие события' },
	{ value: 'intellectual_games', label: 'Интеллектуальные игры' },
	{ value: 'languages', label: 'Иностранные языки' },
	{ value: 'tours_travel', label: 'Экскурсии и путешествия' },
	{ value: 'theaters', label: 'Театры' },
	{ value: 'science', label: 'Наука' },
	{ value: 'sports', label: 'Спорт' },
	{ value: 'hobbies', label: 'Хобби и творчество' },
	{ value: 'beauty_health', label: 'Красота и здоровье' },
	{ value: 'civic_projects', label: 'Гражданские проекты' },
	{ value: 'master_class', label: 'Мастер-классы' }
];
