export const eventTypesDataOptions = {
	concerts: { name: 'Концерты' },
	party: { name: 'Вечеринки' },
	business: { name: 'Бизнес' },
	it_internet: { name: 'Ит и интернет' },
	exhibitions: { name: 'Выставки' },
	cinema: { name: 'Кино' },
	food: { name: 'Еда' },
	education: { name: 'Образование' },
	art_culture: { name: 'Искусство и культура' },
	for_children: { name: 'Для детей' },
	psychology: { name: 'Психология и саморазвитие' },
	other_events: { name: 'Другие события' },
	intellectual_games: { name: 'Интеллектуальные игры' },
	languages: { name: 'Иностранные языки' },
	tours_travel: { name: 'Экскурсии и путешествия' },
	theaters: { name: 'Театры' },
	science: { name: 'Наука' },
	sports: { name: 'Спорт' },
	hobbies: { name: 'Хобби и творчество' },
	beauty_health: { name: 'Красота и здоровье' },
	civic_projects: { name: 'Гражданские проекты' },
	master_class: { name: 'Мастер-классы' }
};
