name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install static adapter
        run: npm install -D @sveltejs/adapter-static

      - name: Configure adapter
        run: |
          echo "import adapter from '@sveltejs/adapter-static';" > svelte.config.js
          echo "export default { kit: { adapter: adapter() } };" >> svelte.config.js

      - name: Build project
        run: |
          npm run build
          touch build/.nojekyll
        env:
          VITE_BASE_PATH: "/${{ github.event.repository.name }}"  # Для корневых путей

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4